workspace:
  base: /app
  path: toolkit

      
matrix:
  FPFIS_PHP_VERSION:
    - 56
    - 71

services:
  itop:
    image: vbkunin/itop:2.3.4
    commands: 
      - /run.sh &
      - cp tests/itop_toolkit/* /app/toolkit/
      - cd /app/toolkit/
      - sleep 10
      - /usr/bin/php /app/toolkit/unattended_install.php default-params.xml
      - chmod 775 -R /app/conf
      - sleep 3600

pipeline:
  test-composer-deps:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    commands:
      - composer global require sensiolabs/security-checker
      - ~/.composer/vendor/bin/security-checker security:check

  prepare:
    # Use php${FPFIS_PHP_VERSION} image
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    commands:
      - php --version
      - composer install

  # Run parallel tests ( groups ) :
  test-phpunit:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    group: test
    commands:
      - wget http://itop
      - ./vendor/bin/phpunit
      

  test-phpcs:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    group: test
    commands:
      - ./vendor/bin/phpcs -p