workspace:
  base: /test
  path: fpfismanager

matrix:
  FPFIS_PHP_VERSION:
    - 56
    - 71

pipeline:
  test-composer-deps:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    commands:
      - composer global require sensiolabs/security-checker
      - ~/.composer/vendor/bin/security-checker security:check

  prepare:
    # Use php${FPFIS_PHP_VERSION} image
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    commands:
      - php --version
      - composer install

  # Run parallel tests ( groups ) :
  test-phpunit:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    group: test
    commands:
      - ./vendor/bin/phpunit

  test-phpcs:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    group: test
    commands:
      - ./vendor/bin/phpcs -p