services:
  - docker

before_install:
- docker pull vbkunin/itop:2.3.4
- ls -la
- docker run -d -v $(pwd)/unattended_install.php:/app/toolkit/unattended_install.php $(pwd)/default-params.xml:/app/toolkit/default-params.xml vbkunin/itop:2.3.4 --name=my-itop 
- docker ps -a
- docker exec my-itop "cd /app/toolkit; php /app/toolkit/unattended_install.php default-params.xml"
- docker ps -a

language: php
php:
  - 5.6
  - hhvm
  - 7.0
before_script:
  - composer self-update
  - composer install
script:
  - composer phpcs
  - composer phpunit
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
