language: php
php:
  - 5.6
  - hhvm
  - 7.0
before_script:
  - composer self-update
  - composer install
script:
  - php vendor/bin/phpunit
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: 7.0
