services:
  - docker

before_install:
- docker pull vbkunin/itop:2.3.4
- docker run -d vbkunin/itop:2.3.4 --name=my-itop 
- docker ps -a
- docker exec my-itop "mkdir /app/toolkit"
- docker cp tests/itop_toolkit/unattended_install.php my-itop:/app/toolkit/unattended_install.php
- docker cp tests/itop_toolkit/default-params.xml my-itop:/app/toolkit/default-params.xml
- docker exec my-itop "cd /app/toolkit; php /app/toolkit/unattended_install.php default-params.xml"
- docker ps -a

language: php
php:
  - 5.6
  - hhvm
  - 7.0
before_script:
  - composer self-update
  - composer install
script:
  - composer phpcs
  - composer phpunit
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
