services:
  - docker

before_install:
- docker pull vbkunin/itop:2.3.4
- docker run -d --name=my-itop -p 80:80 -v $(pwd)/tests/itop_toolkit/unattended_install.php:/app/toolkit/unattended_install.php -v $(pwd)/tests/itop_toolkit/default-params.xml:/app/toolkit/default-params.xml vbkunin/itop:2.3.4
# Wait for mysql fully started
- sleep 10
- docker exec my-itop bash -c "cd /app/toolkit; php /app/toolkit/unattended_install.php default-params.xml"
- docker exec my-itop bash -c "chmod 775 -R /app/conf"
- docker ps -a

language: php
php:
  - 5.6
  - 7.0
before_script:
  - composer self-update
  - composer install
script:
  - vendor/bin/security-checker security:check
  - composer phpcs
  - composer phpunit
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
