language: php
php:
  - 5.6
  - hhvm
  - nightly
before_script:
  - composer self-update
  - composer install
  - php -r"echo file_get_contents('https://www.google.com/');"
script:
  - php vendor/bin/phpunit
